version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install pipenv
  pre_build:
    commands:
      - pipenv install --dev
      - pipenv run pytest --cov=src -v -s --cov-fail-under=70
  build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Building the Docker image..."
      - docker build -t blacklist ./blacklist
      - echo "Tagging the Docker image..."
      - docker tag blacklist:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/blacklist:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/blacklist:latest
artifacts:
  files:
    - '**/*'